#!/usr/bin/env bash
# Bash script to display information about
# subdomains

domain_information() {
	dig "$2"."$1" | grep -A1 'ANSWER SECTION' | tail -n 1 | awk '{print "The subdomain '$2' is a " $4 " record and points to " $5}'
}

if [ "$#" -eq 1 ]
then
  domain_information "$1" "www"
  domain_information "$1" "lb-01"
  domain_information "$1" "web-01"
  domain_information "$1" "web-02"
elif [ "$#" -eq 2 ]
then
  domain_information "$1" "$2"
fi

