#!/usr/bin/env bash
# Bash script to transfer a file from a client
# to a server.
# Accepts 4 arguments:
# 	Arg 1: Path to the file to be transferred.
#	Arg 2: IP of th server to transfer the files to.
#	Arg 3: username to connect with.
#	Arg 4: path to SSH private key to use.
if [$# -lt 4]
then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
	scp -i "$4" "$1" "$3"@"$2":~
fi
