#!/usr/bin/env bash
# Script to install and configure Nginx on a server

sudo apt-get -y update 
sudo apt-get -y install nginx
sudo ufw allow "Nginx HTTP"
echo 'Hello World' | sudo tee /var/www/html/index
sudo service nginx start
