#!/usr/bin/env bash
# script to configure an Nginx server so that
# /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World' | sudo /var/www/html/index
sudo sed -i '/listen 80 default_server/a rewrite ^/redirect_me https://www.youtube.com/watch?v=dQw4w9WgXcQ/ permanent;' /etc/nginx/sites-available/default
sudo service nginx restart
