#!/usr/bin/env bash
# script to configure an Nginx server so that
# /redirect_me is redirecting to another page

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo 'Hello World' | sudo /var/www/html/index
sudo sed -i '/listen 80 default_server/a location /redirect_me { \n rewrite https://www.youtube.com/watch?v=dQw4w9WgXcQ/ permanent; \n}' /etc/nginx/sites-enabled/default
sudo service nginx restart
