#!/usr/bin/env bash
# Script to configure an Nginx server to have a
# custom 404 page.

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
lines="\\\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t}"
sudo sed -i "27i $lines" /etc/nginx/sites-available/defualt
sudo service nginx restart
