#!/usr/bin/env bash
# Bash script for installing nginx and performing configurations

sudo apt-get -y update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
touch /var/www/html/404.html
echo "Ceci n'est pas une page" > /var/www/html/404.html

printf %s "server {
	listen 80 default_server;
	listen [::]:80 default_server;
	
	root /var/www/html;
	index index.html index.htm;

	server_name _;
	add_header X-Served-By $HOSTNAME;
	location / {
		try_files $uri $uri/ =404;
	}
	
	location /redirect_me {
		rewrite ^ https://www.youtube.com/watch?v=dQw4w9WgXcQ permanent;
	}

	error_page 404 404.html;
	location /404 {
		root /var/www/html;
		internal;
	}
}" > /etc/nginx/sites-available/default

sudo service nginx restart
