#!/usr/bin/env bash
# Bash script to install and configure a load
# balancer using haproxy

sudo apt-get -y install software-properties-common
sudo add-apt-repository ppa:vbernat/haproxy-2.0
sudo apt-get -y update

sudo apt-get -y install haproxy
sudo sed -i -e '$aENABLED=1\n' /etc/default/haproxy
sudo sed -i -e '$a\listen http-in\n\tbind :80\n\tbalance roundrobin\n\tserver 14492-web-01 3.89.146.205:80 check\n\tserver 14492-web-02 54.88.206.128:80 check\n' /etc/haproxy/haproxy.cfg
sudo service haproxy restart
