#!/usr/bin/env bash
# Bash script to generate a MySQL dump and creates a compressed archive

sudo mysqldump -uroot -p '$1' --all-databases > backup.sql
tar -cvzf "$(date + %d-%m-%Y)".tar.gz ./backup.sql
