#!/usr/bin/bash
# Bash Script to debug a server so that it is able to listen
# on port 80

sudo rm /etc/nginx/sites-enabled/default
sudo ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
