#!/usr/bin/env bash
# script to display the content of the file /etc/passwd

while read -r line
do

	username=$(echo "$line" | cut -d ':' -f1)
	userid=$(echo "$line" | cut -d ':' -f3)
	homedir=$(echo "$line" | cut -d ':' -f7)
	echo -n "$username:"
	echo -n "$userid:"
	echo "$homedir"

done < /etc/passwd
