#!/usr/bin/env bash

count=0

while [ $count -lt 10 ]
do 
	count=$[$count+1]

	if [ $count -eq 4 ]
	then
		echo "bad luck"
		continue
	elif [ $count -eq 8 ]
	then
		echo "good luck"
		continue
	else
		echo "Best School"
		continue
	fi
done
