#!/usr/bin/env bash
# bash script to demonstrate the use of a switch statement

count=1

while [ $count -lt 21 ]
do
	echo "$count"

	case $count in
		4)
			echo "bad luck from China"
			;;
		9)
			echo "bad luck from Japan"
			;;
		17)
			echo "bad luck from Italy"
			;;
	esac

	(( count++ ))
done
