#!/usr/bin/env bash
# bash script to demonstrate the use of file test operators

fileName="school"

if [ -e $fileName ]
then
	echo "school file exists"
	if [ -s $fileName ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f $fileName ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi 
