#!/usr/bin/env bash
# Bash script to configure a ufw to block all incoming
#+ except for ssh, http and https connections.

sudo apt-get install -y ufw
sudo ufw enable
sudo ufw default deny incoming
sudo ufw default allow outgoing
sudo ufw allow ssh
sudo ufw allow http
sudo ufw allow https
